### ISSUE TITLE
Additional Text Metadata necessary

### ISSUE THREAD

**Issue by PaulOpu** [kushalkafle/DVQA_dataset#1]
Hi,
I just wanted to ask if it is possible to receive additional metadata information about the text orientation (horizontal, vertical, diagonally) and if a line break is in the title. Is that possible? Thank you!

**Comment by kushalkafle** [comment]
Text orientation should be possible for me to extract. I will double check and try to update the field in the next few weeks. In the meanwhile, you should be able to deduce the orientation using the bbox information by some simple math observing width/height and a simple script. The horizontal will have all xlabel texts same height regardless of how long the text is, the vertical will have all the same "width" and the diagonal will depend on the length of the text.

 However, I do no think there is any easy to way to detect the line-break in the title, unfortunately.
